docs/pull_request_template.md
=> belindas-closet-nestjs_4_1_pr-template

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md
=> belindas-closet-nestjs_4_2_issue-templates

.env.sample, .gitignore, package-lock.json, package.json, src/app.module.ts
=> belindas-closte-nestjs_4_5_initial-db-connection

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
Resolves #7 
Added prompt to link issues and include tutorials to issue template.
=> belindas-closet-nestjs_4_7_edit-issue-template

.eslintrc.js, src/app.module.ts, src/products/products.controller.spec.ts, src/products/products.controller.ts, src/products/products.module.ts, src/products/products.service.spec.ts, src/products/products.service.ts, src/products/schemas/product.schema.ts
Resolves: #11 | #12 | #13
Created a product schema, service class-model injection, and controller.
This is a simple scalable CRUD application using NestJS Mongoose - connected to the local MongoDB instance.
To test the CRUD you will need to create a `.env` file with the variables below:
> MONGODB_URI=mongodb+srv://`username`:`password`@cluster0.redefo6.mongodb.net/productdb
> NEXTAUTH_URL=http://localhost:3000
> NEXTAUTH_SECRET=secret
_Please replace the username and password to connect to your local MongoDB instance._
**Test POST method:**
**Test GET method:**
_Find All_
_Find One_
**Test PUT method:**
**Test DELETE method:**
=> belinda-nestjs-5-11_12_13-schema_service_controller_creation

.github/workflows/cd-production.yml, .github/workflows/cd-staging.yml, .github/workflows/ci.yml, .github/workflows/on-new-branch.yml, .github/workflows/on-pull-request.yml, .github/workflows/on-push-staging.yml, .github/workflows/sync-staging.yml, package.json
=> belindas-closet-nestjs-5-15-ci-pipeline-creation

src/user/controllers/user/user.controller.ts, src/user/services/user/user.service.ts
Resolves #22 
This is directly related to my previous PR #32
I set up the logging the same, but as the UserModule is not included in `app.module`:
we cannot make calls to the User Controller.
=> belindas-closet-nestjs_1_22_refactor-user-console.log

logger/winston.logger.ts, package-lock.json, package.json, src/app.module.ts, src/main.ts, src/products/controllers/products/products.controller.ts, src/products/services/products/products.service.ts
Resolves #21 
I have installed Winston and set up a logger for the project.
The logger is customized for the development environment and the production environment.
Looking for review if this is what the team would like.
To test:
- Pull the branch and run `npm install` or `yarn install` depending on your package manager.
- In your .env file make sure to set the following variables as detailed in the [installation](https://github.com/SeattleColleges/belindas-closet-nestjs/wiki/Installation) instructions for this repo.
- You must have a valid `MONGODB_URI` string for a database connection.
- You must set the `JWT_SECRET` to 'jwt'.
- Using the available API calls in the `ProductController`, use CURL or Postman to test.
- \* Some calls may require a valid JWT_TOKEN
Here is a screenshot of the …
=> belindas-closet-nestjs _1_21_refactor-product-console.log

src/app.module.ts, src/auth/jwt.guard.ts, src/auth/role.guard.ts, src/auth/roles.decorator.ts, src/products/controllers/products/products.controller.ts, src/products/services/products/products.service.ts
Resolves #24
We want to restrict product creation, updating, and deleting to users with an 'admin' role only.
I implemented the JWT strategy that was already in place, making it so a registered user is required to create, update, or delete a product, which means a valid JWT token is required as an authorization token.
You can generate a JWT token when you either sign-up a user (which creates a user) or login an existing user.
I then implemented a role decorator and guard, so that only a user with an admin role can create, update, or delete a product.
To test:
- In your .env file make sure to set the following variables as detailed in the [installation](https://github.com/SeattleColleges/belindas-closet-nestjs/wiki/Installation) instructions for this repo.
- You must have a valid MongoDB …
=> belindas-closet-nestjs_2_24_admin-role

src/auth/dto/forgot-password.dto.ts
Resolves #37 
Create forgot password Dto in the auth module
=> belinda-nestjs-02-37-forgot_password_dto_creation

src/auth/dto/forgot-password.dto.ts, src/auth/services/auth.service.ts
Resolves #38 
Create a forgot password service in the auth module
=> belinda_nestjs-02-38-forgot_password_service_creation

src/auth/controllers/auth.controller.ts, src/auth/dto/forgot-password.dto.ts, src/auth/services/auth.service.ts
Resolves #39 
Create a forgot password controller in the auth module
=> belinda_nestjs-02-39-forgot_password_controller

src/auth/dto/signup.dto.ts, src/auth/services/auth.service.ts, src/user/controllers/user/user.controller.ts, src/user/schemas/user.schema.ts, src/user/services/user/user.service.ts
Resolves #46 
As a developer, I want to modify the user and sign-up module in the backend to match with the frontend. This will allow proper input retrieval.
Currently, frontend has first name and last name as user name input fields, the backend also has to match this input format.
- Modify necessary files related to the user and sign up.
This issue is related to the signup function
[https://github.com/SeattleColleges/belindas-closet-android/issues/139](https://github.com/SeattleColleges/belindas-closet-android/issues/139)
**Sign Up**
**User in the DB**
=> belinda_nestjs_46_update-user-schema

src/auth/dto/login.dto.ts, src/user/controllers/user/user.controller.ts, src/user/dto/update-user.dto.ts, src/user/services/user/user.service.ts
Resolves #50 
This PR relates to PR #48 and issue #47 
I created a DTO to update a user, added this to the Controller, and removed unnecessary addUser methods from the Service and Controller.
This only affects the `updateUser` methods in the Controller and the Service.
To test, run the app locally and try to update an existing User in Postman.
=> Belinda's-Closet-NestJS_3_50_refactor-User-to-DTO

.github/workflows/on-pull-request.yml, src/main.ts
Testing ci workflow for new pull request
=> Belindas-Closet-nestjs_3_Test-CI-pr-workflow_01

src/products/controllers/products/products.controller.ts
Resolves #52 
This PR relates to PR #44 and issue #45
I removed the `try/catch` blocks and the parameter `@Res response : any` from the methods.
Tested everything in Postman, all behavior is the same.
=> Belinda's-Closet-NestJS_3_52_refactor-product-controller

src/user/controllers/user/user.controller.spec.ts, src/user/controllers/user/user.controller.ts, src/user/services/user/user.service.spec.ts, src/user/services/user/user.service.ts, src/user/user.module.ts
Resolves #47 
I started the testing for the User Controller and Service and was thinking the User needs to be refactored to use Data Transfer Objects (DTOs). We currently use a [DTO](https://github.com/SeattleColleges/belindas-closet-nestjs/blob/main/src/auth/dto/signup.dto.ts) to signup a User and [one](https://github.com/SeattleColleges/belindas-closet-nestjs/blob/main/src/auth/dto/login.dto.ts) to login a User in the [Auth Controller](https://github.com/SeattleColleges/belindas-closet-nestjs/blob/main/src/auth/controllers/auth.controller.ts), and we also use a [DTO](https://github.com/SeattleColleges/belindas-closet-nestjs/blob/main/src/products/dto/create-product.dto.ts) to create a product and [one](https://github.com/SeattleColleges/belindas-closet-nestjs/blob/main/src/products/dto/u …
=> Belinda's-Closet-NestJS_3_47_Unit-Tests-User-Controller-and-Service

src/products/controllers/products/products.controller.ts, src/products/dto/create-product.dto.ts, src/products/dto/update-product.dto.ts, src/products/schemas/product.schema.ts, src/products/services/products/products.service.ts
Resolves #57 
This PR adds the isSold property to the product controller which is used for the archive functionality.
Results on Postman of using the archive API endpoint:
Results of archive in MongoDB:
Linked to [#103](https://github.com/SeattleColleges/belindas-closet-android/issues/103) from [belindas-closet-android](https://github.com/SeattleColleges/belindas-closet-android)
=> belindas-closet-nestjs_3_57_add-issold-property

src/products/services/products/products.service.ts
Resolves #60 
This PR updates the archive function to take in ObjectId as the id parameter, and works in accordance with the archive functionality in the frontend.
Relates to [#165](https://github.com/SeattleColleges/belindas-closet-android/issues/165) from [belindas-closet-android](https://github.com/SeattleColleges/belindas-closet-android)
=> belindas-closet-nestjs_3_60_add-archive-functionality-to-button

src/products/controllers/products/products.controller.spec.ts, src/products/dto/create-product.dto.ts, src/products/dto/update-product.dto.ts, src/products/schemas/product.schema.ts, src/products/services/products/products.service.spec.ts
Resolves #59 
References front end [User Story 172](https://github.com/SeattleColleges/belindas-closet-android/issues/172)
References front end [User Story 168](https://github.com/SeattleColleges/belindas-closet-android/issues/168)
This PR refactors the Product Entity to match the back end. This required changing the Product Schema, the unit testing for the Controller and the Service, and the DTOs that Create a Product and Update a Product.
To test:
- In your .env file make sure to set the following variables as detailed in the [installation](https://github.com/SeattleColleges/belindas-closet-nestjs/wiki/Installation) instructions for this repo.
- You must have a valid MongoDB URI string for a database connection and set it as `MONGODB_URI=<your database connection string>` in your …
=> belinda's-closet_3_refactored-product_59

src/products/dto/create-product.dto.ts
Resolves #76
I will modify the backend's data type in the **create-product.dto.ts** to match the enum type in the front end.
Example JSON new product:
```
{
"productType": "Shoes",
"productGender": "MALE",
"productSizeShoe": 6,
"productSizes": "S",
"productSizePantsWaist": 32,
"productSizePantsInseam": 30,
"productDescription": "High-quality smartwatch with fitness tracking features. Suitable for both men and women.",
"productImage": "https://example.com/product-image.jpg",
"isHidden": false,
"isSold": false
}
=> belinda-closet-nestjs-02-76-change_product_props_enum-01

src/products/services/products/products.service.spec.ts, src/products/services/products/products.service.ts
Resolves #74 
Resolves #35
This PR updates the `findOne` and `updateProduct` functions in the Product Service to validate that the id parameter is a valid Mongoose id. This also updates the error handling to be more concise. Finally it updates the unit testing for those functions.
To test:
- In your .env file make sure to set the following variables as detailed in the [installation](https://github.com/SeattleColleges/belindas-closet-nestjs/wiki/Installation) instructions for this repo.
- You must have a valid MongoDB URI string for a database connection and set it as `MONGODB_URI=<your database connection string>` in your `.env`.
- You must set `JWT_SECRET=jwt` in your`.env`.
- You must set an expiry for your JWT Secret, I did `JWT_EXPIRES = 90d` in your `.env`.
- Using the available API …
=> belinda's-closet-nestjs_5_74_refactor-update-find-and-unit-tests

src/products/controllers/products/products.controller.ts
Resolves #78 
I want to update the add product endpoint to allow users with the CREATOR role to add new products from the front end.
=> belinda-closet-nestjs-02-78-creator_add_products_endpoint

.github/ISSUE_TEMPLATE/issue.md, .github/ISSUE_TEMPLATE/pull_request.md, .github/ISSUE_TEMPLATE/user_story.md
resolves #80 
This PR is for adding the user story, issue and pull request templates to the nestjs repo.
=> Belindas-closet-nestjs-2-80-create-templates-for-nestjs

.github/ISSUE_TEMPLATE/issue.md, .github/ISSUE_TEMPLATE/pull_request.md, .github/ISSUE_TEMPLATE/user_story.md
resolves #84 
This PR adds front matter to templates which will allow it to be used in GitHub.
=> belindas-closet-nestjs-2-84-add-front-matter-to-nestjs

src/auth/controllers/auth.controller.ts, src/auth/decorator/user.decorator.ts, src/auth/dto/change-password.dto.ts, src/auth/dto/product-key.dto.ts, src/auth/services/auth.service.ts
Resolves #88 
Related [#250](https://github.com/SeattleColleges/belindas-closet-nextjs/issues/250)
This pull request introduces a new API endpoint for changing passwords. It receives a password change request from the front-end and processes the update of the new password.
**Approach:**
- Refactored the unused generate key function to the change password function
- Created a user decorator that allows access to user properties.
- Reference: [GitHub Repo](https://github.com/Abraham-hanks/Magscollectivity/blob/master/src/modules/auth/decorator/user.decorator.ts)
- Implemented logic in service and controller
**To test:**
- Ensure the backend is running
- Use the API endpoints
- `http://localhost:3000/api/auth/login` - To log in first and copy the JWT token
- …
=> belinda-nestjs-04-88-implement-change-password

src/products/controllers/products/products.controller.spec.ts, src/products/controllers/products/products.controller.ts, src/products/dto/create-product.dto.ts, src/products/dto/update-product.dto.ts, src/products/schemas/product.schema.ts, src/products/services/products/products.service.spec.ts, src/products/services/products/products.service.ts
Resolves #97 
Related #96 
I would like to add the user's identity as an owner of the product. This will enable us to keep track of the product's creator and allow the owner to make necessary edits.
**Add product by the creator (last 4 digits user ID: 6058)**
**Update product by the admin (last 4 digits user ID: 6055)**
**Finding the product by ID to see the result**
**Run test**
=> belinda-nest-4-97-adding-product-owner-01

DATABASE.md, env.production
Resolves issue #111
This pull request is a dummy .env file that displays to the developers the information required to be able to connect to Belinda's closet database, and interact with it through the front end.
Edit:
This is PR is actually a mistake rooted in a misunderstanding of how the database connects to the front end. This PR describes the steps on how to get the ec2 instance to connect to the devs developer environment on localhost. The database is already connected to the deployed Belinda's closet website and the changes were to be made on the EC2 instance rather than in our codebase on Github. I learned that the database is actually talking to the front end website through SSH on the AWS EC2 instances CLI, whereas I was trying to connect to the db through my own local computer. …
=> Database integration for user and product management: Connect NestJS to the Cloud database dummy .env

.github/workflows/ssh.yml
Resolves #131 
This RP will add a yml file to process the CD for the backend deployed server.
**Successful pull code from the main branch
Successful install and use of the latest node version**
**Successful install and restart PM2 for new node**
=> belinda-nestjs-07-add-CD

src/auth/controllers/auth.controller.spec.ts, src/auth/controllers/auth.controller.test.ts, src/auth/dto/signup.dto.ts, src/auth/services/auth.service.ts, src/user/controllers/user/user.controller.spec.ts, src/user/controllers/user/user.controller.ts, src/user/dto/update-user.dto.ts, src/user/schemas/user.schema.ts, src/user/services/user/user.service.spec.ts, src/user/services/user/user.service.ts
Resolves #137
This PR adds backend functionality for Pronouns in the frontend.
=> belindas-closet-nestjs_10_137_add-pronouns-to-backend

env.example, src/main.ts
This PR contains a quality of life update! Now you can set the API address from your .env file.
How to test:
- Use the .env.sample to help set up your .env file. Once set,  run backend and use postman or frontend (next.js) to make API calls to the server
- Make sure localhost port number matches with backend port number if using frontend
=> update app port listener with .env variable

post-issue-smartsheet.py
Reverts SeattleColleges/belindas-closet-nestjs#151
=> Revert "belindas-closet-nestjs_15_150_post_issue_smartsheet"

.github/workflows/auto-assign-issues.yml, .github/workflows/on-new-issue.yaml, post-issue-smartsheet.py
Resolves #157 
This PR fixes the smartsheet script and adjusts the actions. Refer to the issue for a detailed list of changes.
=> belindas-closet-nestjs_16_157_github_actions_adjustments_nestjs

.env.example, package-lock.json, package.json, src/auth/controllers/auth.controller.ts, src/auth/dto/reset-password.dto.ts, src/auth/email-templates/reset-password.ts, src/auth/services/auth.service.ts, src/user/schemas/user.schema.ts
- **Resolves:** #169 
- **Summary:** (Briefly describe what this PR does)
- 🔨 Replaces the SendGrid-based temporary-password flow with a token-based reset link sent via AWS SES
- 👀 Users now click a secure link to set a new password instead of copy/pasting temporary credentials
- 🗨️ All existing signup/login/change-password endpoints remain untouched. 
- **Changes:**
- ✅ Installed & configured AWS SDK for SES
- Extended User model with resetPasswordToken & resetPasswordExpires fields
- Updated AuthService.forgotPassword to generate a time-limited token and send it in an SES email (note: sender & 
recipient must be verified in SES sandbox)
- Updated AuthService.resetPassword to validate the token, hash & store the new password, and clear token fields
- Adjusted AuthController routes for …
=> belindas-closet-nestjs_22_169-forgot-password-functionality
